### ISSUE TITLE
Стили текста на карточках

### ISSUE THREAD

**Issue by aralinilya** [cryingjoker/vue-stylekit#1]
https://cryingjoker.github.io/vue-stylekit/docs/cards

![image](https://user-images.githubusercontent.com/17784592/45449924-45cfab00-b6df-11e8-897e-17c7219352a2.png)
разные стили саблайнов, разный межстрочный, разный размер текста

**Comment by aralinilya** [comment]
![image](https://user-images.githubusercontent.com/17784592/45449980-71eb2c00-b6df-11e8-8c20-e42a1e44570f.png)
Кнопка на карточках нужно меньшего размера типа small которая

**Comment by cryingjoker** [comment]
сейчас везде  line-height: 1.5
размеры - это контент...
межстрочный - это настройки у input сообщения. стоит ли их менять?
