### ISSUE TITLE
https://cryingjoker.github.io/vue-stylekit/docs/promo/tv

### ISSUE THREAD

**Issue by aralinilya** [cryingjoker/vue-stylekit#10]
1. margin top/bottom от бейджей должны быть одинаковыми
![image](https://user-images.githubusercontent.com/17784592/45650400-d985ea80-bad6-11e8-9724-d8d45798b551.png)

2. контент в карточках без отступов
![image](https://user-images.githubusercontent.com/17784592/45650436-f4585f00-bad6-11e8-977d-a9779de0e5e0.png)

**Comment by cryingjoker** [comment]
done
