### ISSUE TITLE
Resolve alias @ for export

### ISSUE THREAD

**Issue by silrage** [cryingjoker/vue-stylekit#11]
Привет, помоги исправить ошибку алиаса "@" для моего внешнего проекта?
Webpack ругается:
`ERROR in d:/apps_2/ui-kit/node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!d:/apps_2/ui-kit/src/app/Content/complex-elements/Card/Card.vue
Module not found: Error: Can't resolve '@/mixins/normalizeVariable' in 'd:\apps_2\ui-kit\src\app\Content\complex-elements\Card'
 @ d:/apps_2/ui-kit/node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!d:/apps_2/ui-kit/src/app/Content/complex-elements/Card/Card.vue 7:25-62
 @ d:/apps_2/ui-kit/src/app/Content/complex-elements/Card/Card.vue
 @ d:/apps_2/ui-kit/src/app/Content/complex-elements/index.js
 @ d:/apps_2/ui-kit/index.js
 @ ./client/components/theme/Content/index.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./client/components/theme/App.vue
 @ ./client/components/theme/App.vue`

Я использую данный проект через npm.

**Comment by cryingjoker** [comment]
завтра думаю проверить v0.02 скорее всего оно решит это и можно тогда и через гит и через npm
