### ISSUE TITLE
UseCase cmp error

### ISSUE THREAD

**Issue by silrage** [cryingjoker/vue-stylekit#118]
Привет. В компоненте use-case есть ошибки:
https://github.com/cryingjoker/vue-stylekit/blob/83c8ff947423146a0c85b37f7635e8c019ce088a/src/lib/components/Card/UseCase.vue#L32
- не указана единица измерения для высоты - 'px'

**Comment by wikked616** [comment]
https://github.com/cryingjoker/vue-stylekit/pull/119

**Comment by silrage** [comment]
:+1:
