### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by silrage** [cryingjoker/vue-stylekit#12]
Жутко не комфортная структура, пробовал руками перенести недостающий в **ui-kit** компонент, не нашёл для него стили. Нет слов про сам процесс экспорта этого мессива в либу ui-kit. То импорты левых файлов, то шрифты не грузятся. Надо что-то с этим делать...

**Comment by cryingjoker** [comment]
ok, сейчас попробую реструктуризировать структуру

**Comment by cryingjoker** [comment]
отрефакторил

**Comment by silrage** [comment]
Уже гораздо лучше, спасибо! Дальше можно будет побить конфиги по сегментам и добавить их компиляцию.
