### ISSUE TITLE
Проблема в компоненте RtSelectOption

### ISSUE THREAD

**Issue by VladimirB-RTRU** [cryingjoker/vue-stylekit#127]
При выборе элемента из списка событие `selected` возвращает объект всегда с `value: undefined`.
Причина этого кроется в этой части кода:
```js
    setSelection(e) {
      this.RtSelect.setValue({ text: this.text, value: `this.key` });
      e.preventDefault();
    },
```
Поле `this.key` не задано ни в родительском компоненте ни в текущем.
Хотя через props пробрасывается переменная `value`, и вместо `this.key` нужно использовать `this.value`.

**Comment by silrage** [comment]
@VladimirB-RTRU актуально?

**Comment by VladimirB-RTRU** [comment]
Замечаний, связанных с этим моментом, не было. Так что думаю что нет.
