### ISSUE TITLE
Работа со шрифтами

### ISSUE THREAD

**Issue by silrage** [cryingjoker/vue-stylekit#13]
При подгрузке шрифтов постоянно выбивает проблемы с кодировкой:
`ERROR in d:/apps_2/ui-kit/assets/fonts/BasisGrotesquePro-Bold-Web.eot
    Module parse failed: Unexpected character '�' (1:0)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/css-loader?sourceMap!./node_modules/vue-loader/lib/style-compiler?{"optionsId":"0","vue":true,"id":"data-v-ce431de4","scoped":true,"sourceMap":true}!./node_modules/less-loader/dist/cjs.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./client/components/theme/Cabinet/Cabinet.vue 7:325543-325632 7:325663-325752`

-Возможно надо в webpack поковырятся :hear_no_evil: .

**Comment by cryingjoker** [comment]
``` {
        test: /\.(jpg|png|webp|gif|otf|ttf|woff|woff2|ani|eot|svg)$/,
        loader: `url-loader`,
        options: {
          name: `[name].[hash:20].[ext]`,
          limit: 10000,
        },
      },``` 

не помогло?

**Comment by silrage** [comment]
Решение с отдельным файлом css гармоничнее, пока :-)
