### ISSUE TITLE
Box-shadow on Hover event in rt-card

### ISSUE THREAD

**Issue by silrage** [cryingjoker/vue-stylekit#262]
Чуваки, если юзаете тени при наведении то вырубайте на тачах!
На мобиле хаверы с тенью могут вызвать не желаемый эффект. Благо пока из явных проблем - это дерганье карточек в каруселе. На страничке /books можно увидеть.

**Comment by cryingjoker** [comment]
поправил в d9e7baf57e8207846f700952baa0a9e80178ac8d , проверь)
