### ISSUE TITLE
Сброс overflow после закрытия Popup в ie11

### ISSUE THREAD

**Issue by srgsrk** [cryingjoker/vue-stylekit#330]
https://github.com/cryingjoker/vue-stylekit/blob/e3ff238f745471742b7f715e953d04ea192d02f3/src/lib/components/Popup/RealPopup.vue#L64-L65

В ie-11 не поддерживается значение **unset**

Может заменить на:
`document.body.style.removeProperty('overflow');
 document.documentElement.style.removeProperty('overflow-y');`

**Comment by wikked616** [comment]
заменил unset на removeProperty
