### ISSUE TITLE
Визуализация сетки

### ISSUE THREAD

**Issue by aralinilya** [cryingjoker/vue-stylekit#4]
Давай сделаем что-то типа такого:
![image](https://user-images.githubusercontent.com/17784592/45450509-28034580-b6e1-11e8-86f7-5a2c43788634.png)

1. заливку только у колонок и еще более прозрачную
2. добавить inset box-shadow как контур.

Для того чтоб она стала более похожа на направляющие.

**Comment by cryingjoker** [comment]
done

**Comment by cryingjoker** [comment]
done

**Comment by aralinilya** [comment]
норм!
