### ISSUE TITLE
Промо секции

### ISSUE THREAD

**Issue by aralinilya** [cryingjoker/vue-stylekit#7]
Нужно в боковом меню добавить раздел Promo
и выкладывать туда примеры секций из промок, можно начать с винка

**Comment by cryingjoker** [comment]
done

**Comment by cryingjoker** [comment]
не правильно сделал... это ты должен делать close

**Comment by aralinilya** [comment]
Я немного не то имел ввиду. Не целиком промки выкладывать,
а по частям. Типа: 
1. секция две колонки, текст слева, картинка справа
2. секция с иконками и 4 колонками текста
3. промосекция (обдложка)
4....
