### ISSUE TITLE
Эффект тайплайна

### ISSUE THREAD

**Issue by aralinilya** [cryingjoker/vue-stylekit#8]
Нужно заверстать такую штуку:
![image](https://user-images.githubusercontent.com/17784592/45452822-b5e22f00-b6e7-11e8-9276-acad7193a5ed.png)

![image](https://user-images.githubusercontent.com/17784592/45452878-cf837680-b6e7-11e8-80ac-7da6b3ea54dc.png)

Витя делал подход нужно синкнуться с ним. Вот: https://codepen.io/silrage/full/JBLEvx/
Короче нужно добавить

**Comment by cryingjoker** [comment]
done
