### ISSUE TITLE
https://cryingjoker.github.io/vue-stylekit/docs/promo/smart-house

### ISSUE THREAD

**Issue by aralinilya** [cryingjoker/vue-stylekit#9]
1. давай попробуем первый экран с картинкой сделать высотой (100vh - шапка) 
2. давай эту картинку сделаем двухслойной, чтоб можно было подкладывать разные скриншоты. Сам телефон нужно не только верхужку а весь, но прятать часть через overflow. Если сделаешь тут легкий паралакс будет шикарно.
![image](https://user-images.githubusercontent.com/17784592/45517281-49823100-b7b6-11e8-8eaa-9a5b78d6ae06.png)

3. картинки в каруселе загружаются очень плохо, через белый фон.
Давай для блока сделаем темный бекграунд. У Вити вроде есть реализация ленивой загрузки через лоурес с блюром. 
![image](https://user-images.githubusercontent.com/17784592/45517321-69b1f000-b7b6-11e8-8fbb-8b4d186b4333.png)

4. тут кажется лишний отступ над карточками или нехватает заголовка:
![image](https://user-images.githubusercontent.com/17784592/45517441-cf9e7780-b7b6-11e8-9bf3-14c14ff922fb.png)

5. Этот блок должен разворачиваться аккардионом после клика на заголовок.
Межстрочное меньше line-height: 1.3;
![image](https://user-images.githubusercontent.com/17784592/45517464-e349de00-b7b6-11e8-8b52-1b602c5221ff.png)

6. Мобильная версия. Удели особое внимание двухколоночным секциям: там где текст слева и телефон справа. Телефон под текст.

7. С карточками проблема в мобильной

**Comment by cryingjoker** [comment]
7 - я их не оптимизировал, теперь проверь

**Comment by aralinilya** [comment]
8. сетка и карточки
![image](https://user-images.githubusercontent.com/17784592/45650563-53b66f00-bad7-11e8-9706-f965df4544cc.png)
